#!/bin/bash
rm -rf a b
mkdir a b
cd $1
bc19compile -d .
mv compiled_bot.js ../a/robot.js
cd ..
cd $2
bc19compile -d .
mv compiled_bot.js ../b/robot.js
cd ..
seed=${3:-$RANDOM}
echo "SEED=$seed"
bc19run -r a -b b -s $seed
rm -rf a b
