#!/bin/bash
dir=$(mktemp -d)
mkdir "$dir/a" "$dir/b"
cd $1
bc19compile -d .
mv compiled_bot.js "$dir/a/robot.js"
cd ..
cd $2
bc19compile -d .
mv compiled_bot.js "$dir/b/robot.js"
cd ..
seed=${3:-$RANDOM}
echo "SEED=$seed"
bc19run -r "$dir/a" -b "$dir/b" -s $seed
rm -rf "$dir"
