#!/bin/bash
if [[ ! -e a ]]; then
    mkdir a
fi
if [[ ! -e b ]]; then
    mkdir b
fi
cd $1
bc19compile -d .
mv compiled_bot.js ../a/robot.js
cd ..
cd $2
bc19compile -d .
mv compiled_bot.js ../b/robot.js
cd ..
seed=${3:-$RANDOM}
echo "SEED=$seed"
bc19run -r a -b b -s $seed

